spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/members/**,/api/v1/login/**,/api/v1/logout/**,/api/v1/refreshToken
          filters:
            - AuthenticationFilter

        - id: activity-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/posts/**,/api/v1/comments/**,/api/v1/likes/**
          filters:
            - AuthenticationFilter

        - id: newsfeed-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/members/**
          filters:
            - AuthenticationFilter

security:
  jwt:
    secret-key: sudomirishoptokensudomirishoptokensudomirishoptoken  # Base 64 디코딩의경우 _ 언더바 안됨. 주의
    tokenValid-time: 1800000 # 액세스토큰 유효시간 30분
    refreshtokenValid-time: 259200000 # 리프레쉬토큰 유효시간 3일

server:
  port: 8083