version: '3.8'

x-common-settings: &common-settings
  restart: always
  env_file: .env
  environment:
    SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
    SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
    SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

services:
  database:
    container_name: mysql_db
    image: mysql:8.0.36
    env_file: .env
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: on-failure
    volumes:
      - ./database/config:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: redis_server
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - ./redis/data:/data

  redis_auth:
    container_name: redis_auth_server
    image: redis:latest
    ports:
      - "6380:6379"
    restart: on-failure
    volumes:
      - ./redis_auth/data:/data

  redis_cache_auth:
    container_name: redis_cache_server
    image: redis:latest
    ports:
      - "6381:6379"
    restart: on-failure
    volumes:
      - ./redis_cache/data:/data

  mongodb:
    container_name: mongodb_server
    image: mongo:latest
    env_file: .env
    ports:
      - "27017:27017"
    restart: on-failure
    volumes:
      - ./mongodb/data/db:/data/db
      - ./mongodb/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --auth

  user-service:
    <<: *common-settings
    container_name: user-service
    build:
      context: ../userService
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
      - redis_auth
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_AUTH_HOST: redis_auth
      SPRING_REDIS_AUTH_PORT: 6380

  activity-service:
    <<: *common-settings
    container_name: activity-service
    build:
      context: ../activityService
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8081:8081"

  newsfeed-service:
    <<: *common-settings
    container_name: newsfeed-service
    build:
      context: ../newsfeedService
      dockerfile: Dockerfile
    depends_on:
      - database
      - mongodb
    ports:
      - "8082:8082"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb_server/${MONGODB_DATABASE}

  apigateway:
    <<: *common-settings
    container_name: apigateway
    build:
      context: ../apiGateway
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  orderpayment-service:
    <<: *common-settings
    container_name: orderpayment-service
    build:
      context: ../orderPaymentService
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8084:8084"

  productmanagement-service:
    <<: *common-settings
    container_name: productmanagement-service
    build:
      context: ../productManagementService
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis_cache_auth
    ports:
      - "8085:8085"
    environment:
      SPRING_REDIS_HOST: redis_cache_auth
      SPRING_REDIS_PORT: 6381
