version: '3.8'

services:
  mysql-container:
    image: mysql:8.0.36
    ports:
      - "3306:3306"
    restart: on-failure
    volumes:
      - mysql_data_volume:/var/lib/mysql
    env_file: .env
    environment:
      - TZ=Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --character-set-client-handshake=FALSE